import React from 'react';
import { Home, Wifi, PhoneCall, GraduationCap, ShieldCheck, Zap, Wallet, Clock, Bell, MessageSquareWarning, BookOpen, User, ShoppingBag, BarChart2, Send, Sliders, DollarSign, Server, Sparkles, ChevronRight, PanelLeftClose, PanelLeftOpen } from 'lucide-react';
import { UserRole } from '../../types';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';

interface SidebarProps { currentRole: UserRole; activeTab: string; onSelectTab?: (tab: string) => void; onTabChange?: (tab: string) => void; unreadNotifications?: number; openComplaintsCount?: number; pendingPayoutsCount?: number; isCollapsed?: boolean; onToggleCollapse?: () => void; }

type NavItem = { id: string; altIds?: string[]; label: string; icon: React.ElementType; badge?: string; count?: number };

export const Sidebar: React.FC<SidebarProps> = ({ currentRole, activeTab, onSelectTab, onTabChange, unreadNotifications = 0, openComplaintsCount = 0, pendingPayoutsCount = 2, isCollapsed = false, onToggleCollapse }) => {
  if (currentRole === 'public' || currentRole === 'storefront') return null;
  const select = (id: string) => { onSelectTab?.(id); onTabChange?.(id); };
  const groups: { group: string; items: NavItem[] }[] = currentRole === 'customer' ? [{ group: 'Workspace', items: [
    { id: 'overview', altIds: ['dashboard'], label: 'Dashboard', icon: Home }, { id: 'buy-data', label: 'Buy Data', icon: Wifi, badge: 'Popular' }, { id: 'buy-airtime', label: 'Buy Airtime', icon: PhoneCall }, { id: 'results-checker', label: 'Results Checker', icon: GraduationCap }, { id: 'afa', label: 'AFA Registration', icon: ShieldCheck, badge: 'Subsidized' }, { id: 'utilities', label: 'Utilities & Bills', icon: Zap }, { id: 'wallet', label: 'Wallet & Ledger', icon: Wallet }, { id: 'orders', label: 'My Orders', icon: Clock }, { id: 'notifications', label: 'Notifications', icon: Bell, count: unreadNotifications }, { id: 'complaints', label: 'Complaints & Help', icon: MessageSquareWarning, count: openComplaintsCount }, { id: 'guides', label: 'How-to Guides', icon: BookOpen }, { id: 'profile', label: 'Profile & Security', icon: User }
  ] }] : currentRole === 'agent' ? [{ group: 'Overview', items: [{ id: 'overview', altIds: ['dashboard'], label: 'Agent Dashboard', icon: Home }, { id: 'my-store', label: 'My Store Builder', icon: ShoppingBag, badge: 'Live' }] }, { group: 'Commerce & Sales', items: [{ id: 'store-orders', label: 'Store Orders', icon: Clock }, { id: 'pricing', label: 'Pricing & Margins', icon: Sliders }, { id: 'analytics', label: 'Sales Analytics', icon: BarChart2 }, { id: 'bulk-sms', label: 'Bulk SMS Campaign', icon: Send }, { id: 'withdraw', label: 'Withdraw Commissions', icon: DollarSign, badge: 'MoMo' }] }] : [{ group: 'Operations & Gateways', items: [{ id: 'gateways', altIds: ['dashboard'], label: 'Carrier Gateways & Latency', icon: Server, badge: 'Live' }, { id: 'orders-audit', altIds: ['order-monitor'], label: 'Orders Audit & Dispatch', icon: Clock }, { id: 'settlement', altIds: ['payouts'], label: 'Settlement & Balances', icon: DollarSign, count: pendingPayoutsCount }] }, { group: 'Services Administration', items: [{ id: 'afa-verification', altIds: ['afa-admin'], label: 'AFA Approvals', icon: ShieldCheck }, { id: 'vouchers-stock', altIds: ['checkers-admin'], label: 'Voucher Stock (WAEC/BECE)', icon: GraduationCap }] }];
  const roleLabel = currentRole === 'admin' ? 'NOC Admin' : currentRole === 'agent' ? 'Agent Portal' : 'Customer Account';
  return <aside className={`fixed inset-y-16 left-0 z-30 flex h-[calc(100vh-4rem)] flex-col border-r border-border bg-card transition-[width] duration-200 ${isCollapsed ? 'w-20' : 'w-64'}`}>
    <div className={`flex items-center border-b border-border/70 p-4 ${isCollapsed ? 'justify-center' : 'justify-between'}`}><div className="flex items-center gap-2"><span className="size-2.5 rounded-full bg-primary" /><span className={`${isCollapsed ? 'sr-only' : ''} text-xs font-bold uppercase tracking-wider text-muted-foreground`}>{roleLabel}</span></div>{onToggleCollapse && <Button variant="ghost" size="iconSm" onClick={onToggleCollapse} aria-label={isCollapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{isCollapsed ? <PanelLeftOpen /> : <PanelLeftClose />}</Button>}</div>
    <nav className="min-h-0 flex-1 overflow-y-auto p-3"><div className="flex flex-col gap-4">{groups.map((group) => <section key={group.group} className="flex flex-col gap-1"><h2 className={`${isCollapsed ? 'sr-only' : ''} px-3 text-[10px] font-bold uppercase tracking-wider text-muted-foreground`}>{group.group}</h2>{group.items.map((item) => { const Icon = item.icon; const active = activeTab === item.id || item.altIds?.includes(activeTab); return <Button key={item.id} variant={active ? 'default' : 'ghost'} size="sm" onClick={() => select(item.id)} title={isCollapsed ? item.label : undefined} aria-label={item.label} className={`w-full justify-start ${isCollapsed ? 'justify-center px-0' : ''}`}><Icon data-icon="inline-start" /><span className={isCollapsed ? 'sr-only' : 'truncate'}>{item.label}</span>{!isCollapsed && item.badge && <Badge variant="secondary" className="ml-auto text-[10px]">{item.badge}</Badge>}{!isCollapsed && item.count ? <Badge variant="destructive" className="ml-auto">{item.count}</Badge> : null}</Button>; })}</section>)}</div></nav>
    {!isCollapsed && currentRole === 'customer' && <div className="m-3 flex flex-col gap-2 rounded-2xl border border-primary/20 bg-primary/10 p-3"><div className="flex items-center gap-1.5 text-xs font-bold"><Sparkles className="size-3.5 text-primary" />Sell data in Ghana</div><p className="text-[11px] leading-snug text-muted-foreground">Launch a branded store and earn from every order.</p><Button variant="link" size="sm" className="justify-start px-0" onClick={() => select('guides')}>Learn more<ChevronRight data-icon="inline-end" /></Button></div>}
  </aside>;
};
export default Sidebar;
