import {
  DataBundle,
  Order,
  Transaction,
  ResultCheckerProduct,
  AfaApplication,
  Complaint,
  AgentStoreConfig,
  PayoutRequest,
  BulkSmsCampaign,
  TelecomNetwork,
  TelecomGateway,
} from "./types";

export const INITIAL_BUNDLES: DataBundle[] = [
  // MTN Ghana Bundles (Non-expiry & Turbonet) - Standard
  {
    id: "mtn-1gb",
    network: "MTN",
    name: "MTN Non-Expiry 1GB",
    sizeGb: 1,
    sizeLabel: "1 GB",
    validity: "Non-Expiry",
    wholesalePrice: 4.8,
    retailPrice: 5.5,
    category: "non_expiry",
    isPopular: false,
    tier: "standard",
  },
  {
    id: "mtn-2.5gb",
    network: "MTN",
    name: "MTN Non-Expiry 2.5GB",
    sizeGb: 2.5,
    sizeLabel: "2.5 GB",
    validity: "Non-Expiry",
    wholesalePrice: 10.5,
    retailPrice: 12.0,
    category: "non_expiry",
    isPopular: true,
    tier: "standard",
  },
  {
    id: "mtn-5gb",
    network: "MTN",
    name: "MTN Non-Expiry 5GB",
    sizeGb: 5,
    sizeLabel: "5 GB",
    validity: "Non-Expiry",
    wholesalePrice: 19.5,
    retailPrice: 22.5,
    category: "non_expiry",
    isPopular: true,
    tier: "standard",
  },
  {
    id: "mtn-10gb",
    network: "MTN",
    name: "MTN Non-Expiry 10GB",
    sizeGb: 10,
    sizeLabel: "10 GB",
    validity: "Non-Expiry",
    wholesalePrice: 38.0,
    retailPrice: 43.0,
    category: "non_expiry",
    isPopular: true,
    tier: "standard",
  },
  {
    id: "mtn-20gb",
    network: "MTN",
    name: "MTN Super Non-Expiry 20GB",
    sizeGb: 20,
    sizeLabel: "20 GB",
    validity: "Non-Expiry",
    wholesalePrice: 72.0,
    retailPrice: 82.0,
    category: "non_expiry",
    isPopular: false,
    tier: "standard",
  },
  {
    id: "mtn-50gb",
    network: "MTN",
    name: "MTN Mega Fiber/Turbonet 50GB",
    sizeGb: 50,
    sizeLabel: "50 GB",
    validity: "60 Days",
    wholesalePrice: 165.0,
    retailPrice: 185.0,
    category: "turbonet",
    isPopular: false,
    tier: "standard",
  },
  {
    id: "mtn-100gb",
    network: "MTN",
    name: "MTN Enterprise Turbonet 100GB",
    sizeGb: 100,
    sizeLabel: "100 GB",
    validity: "90 Days",
    wholesalePrice: 310.0,
    retailPrice: 350.0,
    category: "turbonet",
    isPopular: false,
    tier: "standard",
  },

  // MTN Ghana Xpress Priority Bundles (Express delivery · priority queue)
  {
    id: "mtn-xpress-1gb",
    network: "MTN",
    name: "MTN Xpress 1GB",
    sizeGb: 1,
    sizeLabel: "1 GB",
    validity: "Non-Expiry",
    wholesalePrice: 5.8,
    retailPrice: 6.5,
    category: "non_expiry",
    isPopular: false,
    tier: "xpress",
  },
  {
    id: "mtn-xpress-2.5gb",
    network: "MTN",
    name: "MTN Xpress 2.5GB",
    sizeGb: 2.5,
    sizeLabel: "2.5 GB",
    validity: "Non-Expiry",
    wholesalePrice: 12.2,
    retailPrice: 14.0,
    category: "non_expiry",
    isPopular: true,
    tier: "xpress",
  },
  {
    id: "mtn-xpress-5gb",
    network: "MTN",
    name: "MTN Xpress 5GB",
    sizeGb: 5,
    sizeLabel: "5 GB",
    validity: "Non-Expiry",
    wholesalePrice: 22.0,
    retailPrice: 25.5,
    category: "non_expiry",
    isPopular: true,
    tier: "xpress",
  },
  {
    id: "mtn-xpress-10gb",
    network: "MTN",
    name: "MTN Xpress 10GB",
    sizeGb: 10,
    sizeLabel: "10 GB",
    validity: "Non-Expiry",
    wholesalePrice: 42.5,
    retailPrice: 48.0,
    category: "non_expiry",
    isPopular: true,
    tier: "xpress",
  },
  {
    id: "mtn-xpress-20gb",
    network: "MTN",
    name: "MTN Super Xpress 20GB",
    sizeGb: 20,
    sizeLabel: "20 GB",
    validity: "Non-Expiry",
    wholesalePrice: 79.0,
    retailPrice: 90.0,
    category: "non_expiry",
    isPopular: false,
    tier: "xpress",
  },
  {
    id: "mtn-xpress-50gb",
    network: "MTN",
    name: "MTN Mega Xpress Turbonet 50GB",
    sizeGb: 50,
    sizeLabel: "50 GB",
    validity: "60 Days",
    wholesalePrice: 178.0,
    retailPrice: 200.0,
    category: "turbonet",
    isPopular: false,
    tier: "xpress",
  },
  {
    id: "mtn-xpress-100gb",
    network: "MTN",
    name: "MTN Enterprise Xpress 100GB",
    sizeGb: 100,
    sizeLabel: "100 GB",
    validity: "90 Days",
    wholesalePrice: 340.0,
    retailPrice: 375.0,
    category: "turbonet",
    isPopular: false,
    tier: "xpress",
  },

  // Telecel Ghana Bundles (formerly Vodafone)
  {
    id: "telecel-1.5gb",
    network: "Telecel",
    name: "Telecel Bossu 1.5GB",
    sizeGb: 1.5,
    sizeLabel: "1.5 GB",
    validity: "30 Days",
    wholesalePrice: 5.2,
    retailPrice: 6.0,
    category: "non_expiry",
    isPopular: false,
  },
  {
    id: "telecel-5gb",
    network: "Telecel",
    name: "Telecel Extra 5GB",
    sizeGb: 5,
    sizeLabel: "5 GB",
    validity: "30 Days",
    wholesalePrice: 17.5,
    retailPrice: 20.0,
    category: "non_expiry",
    isPopular: true,
  },
  {
    id: "telecel-10gb",
    network: "Telecel",
    name: "Telecel Extra 10GB",
    sizeGb: 10,
    sizeLabel: "10 GB",
    validity: "30 Days",
    wholesalePrice: 34.0,
    retailPrice: 39.0,
    category: "non_expiry",
    isPopular: true,
  },
  {
    id: "telecel-25gb",
    network: "Telecel",
    name: "Telecel Heavy Surfer 25GB",
    sizeGb: 25,
    sizeLabel: "25 GB",
    validity: "60 Days",
    wholesalePrice: 80.0,
    retailPrice: 92.0,
    category: "special",
    isPopular: false,
  },
  {
    id: "telecel-50gb",
    network: "Telecel",
    name: "Telecel Maxi Ultra 50GB",
    sizeGb: 50,
    sizeLabel: "50 GB",
    validity: "60 Days",
    wholesalePrice: 155.0,
    retailPrice: 175.0,
    category: "special",
    isPopular: false,
  },

  // AirtelTigo / AT Bundles (iShare & Big Time)
  // iShare: Instant delivery · standard validity
  {
    id: "at-ishare-1gb",
    network: "AirtelTigo",
    name: "AT iShare 1GB",
    sizeGb: 1,
    sizeLabel: "1 GB",
    validity: "30 Days",
    wholesalePrice: 4.0,
    retailPrice: 4.8,
    category: "sika",
    isPopular: false,
    tier: "ishare",
  },
  {
    id: "at-ishare-2gb",
    network: "AirtelTigo",
    name: "AT iShare 2GB",
    sizeGb: 2,
    sizeLabel: "2 GB",
    validity: "30 Days",
    wholesalePrice: 6.5,
    retailPrice: 7.5,
    category: "sika",
    isPopular: false,
    tier: "ishare",
  },
  {
    id: "at-ishare-5gb",
    network: "AirtelTigo",
    name: "AT iShare 5GB",
    sizeGb: 5,
    sizeLabel: "5 GB",
    validity: "30 Days",
    wholesalePrice: 15.5,
    retailPrice: 18.0,
    category: "sika",
    isPopular: true,
    tier: "ishare",
  },
  {
    id: "at-ishare-10gb",
    network: "AirtelTigo",
    name: "AT iShare 10GB",
    sizeGb: 10,
    sizeLabel: "10 GB",
    validity: "30 Days",
    wholesalePrice: 29.5,
    retailPrice: 34.0,
    category: "sika",
    isPopular: true,
    tier: "ishare",
  },
  {
    id: "at-ishare-15gb",
    network: "AirtelTigo",
    name: "AT iShare 15GB",
    sizeGb: 15,
    sizeLabel: "15 GB",
    validity: "30 Days",
    wholesalePrice: 44.0,
    retailPrice: 50.0,
    category: "sika",
    isPopular: false,
    tier: "ishare",
  },

  // BigTime: Bulk data · never expires
  {
    id: "at-bigtime-2gb",
    network: "AirtelTigo",
    name: "AT BigTime 2GB",
    sizeGb: 2,
    sizeLabel: "2 GB",
    validity: "Non-Expiry",
    wholesalePrice: 7.0,
    retailPrice: 8.2,
    category: "non_expiry",
    isPopular: false,
    tier: "bigtime",
  },
  {
    id: "at-bigtime-5gb",
    network: "AirtelTigo",
    name: "AT BigTime 5GB",
    sizeGb: 5,
    sizeLabel: "5 GB",
    validity: "Non-Expiry",
    wholesalePrice: 17.0,
    retailPrice: 19.5,
    category: "non_expiry",
    isPopular: true,
    tier: "bigtime",
  },
  {
    id: "at-bigtime-10gb",
    network: "AirtelTigo",
    name: "AT BigTime 10GB",
    sizeGb: 10,
    sizeLabel: "10 GB",
    validity: "Non-Expiry",
    wholesalePrice: 31.5,
    retailPrice: 36.5,
    category: "non_expiry",
    isPopular: true,
    tier: "bigtime",
  },
  {
    id: "at-bigtime-20gb",
    network: "AirtelTigo",
    name: "AT BigTime 20GB",
    sizeGb: 20,
    sizeLabel: "20 GB",
    validity: "Non-Expiry",
    wholesalePrice: 62.0,
    retailPrice: 72.0,
    category: "non_expiry",
    isPopular: false,
    tier: "bigtime",
  },
  {
    id: "at-bigtime-50gb",
    network: "AirtelTigo",
    name: "AT BigTime 50GB",
    sizeGb: 50,
    sizeLabel: "50 GB",
    validity: "Non-Expiry",
    wholesalePrice: 150.0,
    retailPrice: 170.0,
    category: "special",
    isPopular: false,
    tier: "bigtime",
  },
  {
    id: "at-bigtime-100gb",
    network: "AirtelTigo",
    name: "AT BigTime 100GB",
    sizeGb: 100,
    sizeLabel: "100 GB",
    validity: "Non-Expiry",
    wholesalePrice: 290.0,
    retailPrice: 330.0,
    category: "special",
    isPopular: false,
    tier: "bigtime",
  },
];

export const INITIAL_CHECKERS: ResultCheckerProduct[] = [
  {
    id: "waec-wassce",
    title: "WASSCE Result Checker 2026",
    examBody: "WAEC",
    price: 23.0,
    wholesalePrice: 18.0,
    stockCount: 420,
    description:
      "Instant serial & PIN code to check WASSCE school and private results on waecdirect.org",
  },
  {
    id: "cssps-bece",
    title: "BECE Placement Checker 2026",
    examBody: "CSSPS",
    price: 23.0,
    wholesalePrice: 18.0,
    stockCount: 810,
    description:
      "Computerized School Selection and Placement System (CSSPS) Senior High Placement voucher",
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ord-1000a",
    reference: "SDH-GH-2026-94832",
    date: "2026-09-14 17:52",
    customerName: "Kofi Mensah",
    recipientPhone: "0244192834",
    network: "MTN",
    serviceType: "data",
    productName: "MTN Non-Expiry 10GB",
    amount: 48.0,
    paymentMethod: "momo_mtn",
    status: "pending",
    paystackReference: "pstk_sdh94832_live",
    agentMargin: 5.5,
    deliveryTimeline: [
      {
        step: "Order Initiated",
        timestamp: "17:52:00",
        status: "completed",
        note: "Paystack checkout opened",
      },
      {
        step: "Payment Verification",
        timestamp: "Pending",
        status: "pending",
        note: "Customer on Paystack completing payment",
      },
    ],
  },
  {
    id: "ord-1000b",
    reference: "SDH-GH-2026-94833",
    date: "2026-09-14 16:30",
    customerName: "Ama Serwaa",
    recipientPhone: "0502847192",
    network: "Telecel",
    serviceType: "data",
    productName: "Telecel Extra 5GB",
    amount: 20.0,
    paymentMethod: "wallet",
    status: "waiting",
    agentMargin: 2.5,
    deliveryTimeline: [
      {
        step: "Order Placed",
        timestamp: "16:30:00",
        status: "completed",
        note: "Paid via SDH Wallet",
      },
      {
        step: "Dispatch Queue",
        timestamp: "16:30:05",
        status: "current",
        note: "Waiting in upstream dispatch queue",
      },
    ],
  },
  {
    id: "ord-1001",
    reference: "SDH-GH-2026-94812",
    date: "2026-09-11 15:42",
    customerName: "Kojo Mensah",
    recipientPhone: "0244192834",
    network: "MTN",
    serviceType: "data",
    productName: "MTN Non-Expiry 5GB",
    amount: 22.5,
    paymentMethod: "wallet",
    status: "delivered",
    agentMargin: 3.0,
    deliveryTimeline: [
      {
        step: "Order Placed",
        timestamp: "15:42:01",
        status: "completed",
        note: "Paid via SDH Wallet",
      },
      {
        step: "Upstream Dispatch",
        timestamp: "15:42:04",
        status: "completed",
        note: "MTN Direct Core Gateway",
      },
      {
        step: "Network Acknowledged",
        timestamp: "15:42:09",
        status: "completed",
        note: "Batch ID: MTN-ACC-83921",
      },
      {
        step: "Delivered to Beneficiary",
        timestamp: "15:42:15",
        status: "completed",
        note: "Customer balance credited",
      },
    ],
  },
  {
    id: "ord-1002",
    reference: "SDH-GH-2026-94813",
    date: "2026-09-11 16:15",
    customerName: "Akosua Serwaa",
    recipientPhone: "0502847192",
    network: "Telecel",
    serviceType: "data",
    productName: "Telecel Extra 10GB",
    amount: 39.0,
    paymentMethod: "momo_telecel",
    status: "delivered",
    agentMargin: 5.0,
    deliveryTimeline: [
      {
        step: "Order Placed",
        timestamp: "16:15:02",
        status: "completed",
        note: "Paid via Telecel Cash",
      },
      {
        step: "Upstream Dispatch",
        timestamp: "16:15:06",
        status: "completed",
        note: "Telecel Business E-Load",
      },
      {
        step: "Delivered to Beneficiary",
        timestamp: "16:15:18",
        status: "completed",
        note: "Delivered",
      },
    ],
  },
  {
    id: "ord-1003",
    reference: "SDH-GH-2026-94814",
    date: "2026-09-13 17:50",
    customerName: "Emmanuel Osei",
    recipientPhone: "0244192834",
    network: "MTN",
    serviceType: "checker",
    productName: "WASSCE Result Checker 2026",
    amount: 24.0,
    paymentMethod: "wallet",
    status: "delivered",
    voucherCode: "9841-2094-1849",
    voucherSerial: "W26-849102",
    deliveryTimeline: [
      { step: "Order Placed", timestamp: "17:50:10", status: "completed" },
      {
        step: "Voucher Generated",
        timestamp: "17:50:12",
        status: "completed",
        note: "Delivered to customer drawer",
      },
    ],
  },
  {
    id: "ord-1004",
    reference: "SDH-GH-2026-94815",
    date: "2026-09-11 16:50",
    customerName: "Yaw Boateng",
    recipientPhone: "0553920194",
    network: "MTN",
    serviceType: "data",
    productName: "MTN Non-Expiry 2.5GB",
    amount: 12.0,
    paymentMethod: "momo_mtn",
    status: "processing",
    deliveryTimeline: [
      {
        step: "Order Placed",
        timestamp: "16:50:04",
        status: "completed",
        note: "MTN MoMo Debit Verified",
      },
      {
        step: "Upstream Dispatch",
        timestamp: "16:50:08",
        status: "completed",
        note: "Queued at MTN EVD",
      },
      {
        step: "Network Acknowledged",
        timestamp: "16:50:22",
        status: "current",
        note: "Awaiting network SMS confirm",
      },
      {
        step: "Delivered to Beneficiary",
        timestamp: "Pending",
        status: "pending",
      },
    ],
  },
  {
    id: "ord-1005",
    reference: "SDH-GH-2026-94816",
    date: "2026-09-11 16:58",
    customerName: "Priscilla Addo",
    recipientPhone: "0277382910",
    network: "AirtelTigo",
    serviceType: "airtime",
    productName: "AT Airtime Top-up",
    amount: 20.0,
    paymentMethod: "wallet",
    status: "delivered",
    deliveryTimeline: [
      { step: "Order Placed", timestamp: "16:58:00", status: "completed" },
      { step: "E-Load Dispatched", timestamp: "16:58:03", status: "completed" },
      {
        step: "Delivered",
        timestamp: "16:58:08",
        status: "completed",
        note: "GH₵20.00 Credited",
      },
    ],
  },
  {
    id: "ord-1006",
    reference: "SDH-GH-2026-94817",
    date: "2026-09-13 17:45",
    customerName: "Kojo Mensah",
    recipientPhone: "0244192834",
    network: "MTN",
    serviceType: "checker",
    productName: "BECE Placement Checker 2026",
    amount: 15.0,
    paymentMethod: "wallet",
    status: "processing",
    voucherCode: "4810-5829-1092",
    voucherSerial: "B26-102948",
  },
  {
    id: "ord-1007",
    reference: "SDH-GH-2026-94818",
    date: "2026-09-13 17:40",
    customerName: "Akosua Serwaa",
    recipientPhone: "0244192834",
    network: "Telecel",
    serviceType: "checker",
    productName: "WASSCE Result Checker 2026",
    amount: 24.0,
    paymentMethod: "momo_telecel",
    status: "failed",
    voucherCode: "1029-4820-9581",
    voucherSerial: "W26-992014",
  },
  {
    id: "ord-1008",
    reference: "SDH-GH-2026-94819",
    date: "2026-09-13 17:35",
    customerName: "Yaw Boateng",
    recipientPhone: "0244192834",
    network: "MTN",
    serviceType: "checker",
    productName: "NOVDEC Result Checker 2026",
    amount: 28.0,
    paymentMethod: "wallet",
    status: "delivered",
    voucherCode: "3910-4829-1058",
    voucherSerial: "N26-440192",
  },
  {
    id: "ord-1009",
    reference: "SDH-GH-2026-94820",
    date: "2026-09-13 17:30",
    customerName: "Priscilla Addo",
    recipientPhone: "0244192834",
    network: "AirtelTigo",
    serviceType: "checker",
    productName: "BECE Placement Checker 2026",
    amount: 15.0,
    paymentMethod: "wallet",
    status: "processing",
    voucherCode: "8392-1049-5829",
    voucherSerial: "B26-382910",
  },
  {
    id: "ord-1010",
    reference: "SDH-GH-2026-94821",
    date: "2026-09-13 17:25",
    customerName: "Kojo Mensah",
    recipientPhone: "0244192834",
    network: "MTN",
    serviceType: "checker",
    productName: "WASSCE Result Checker 2026",
    amount: 24.0,
    paymentMethod: "wallet",
    status: "failed",
    voucherCode: "5829-1049-3920",
    voucherSerial: "W26-102938",
  },
  {
    id: "ord-1011",
    reference: "SDH-GH-2026-94822",
    date: "2026-09-09 10:00",
    customerName: "Emmanuel Osei",
    recipientPhone: "0249821034",
    network: "MTN",
    serviceType: "checker",
    productName: "WASSCE Result Checker 2026",
    amount: 24.0,
    paymentMethod: "wallet",
    status: "delivered",
    voucherCode: "9201-4829-1058",
    voucherSerial: "W26-482910",
  },
  {
    id: "ord-1012",
    reference: "SDH-GH-2026-94823",
    date: "2026-09-09 12:30",
    customerName: "Akosua Serwaa",
    recipientPhone: "0502847192",
    network: "Telecel",
    serviceType: "checker",
    productName: "BECE Placement Checker 2026",
    amount: 15.0,
    paymentMethod: "momo_telecel",
    status: "processing",
    voucherCode: "1049-5829-3920",
    voucherSerial: "B26-582910",
  },
  {
    id: "ord-1013",
    reference: "SDH-GH-2026-94824",
    date: "2026-09-08 15:20",
    customerName: "Yaw Boateng",
    recipientPhone: "0553920194",
    network: "MTN",
    serviceType: "checker",
    productName: "WASSCE Result Checker 2026",
    amount: 24.0,
    paymentMethod: "wallet",
    status: "delivered",
    voucherCode: "4829-1058-3920",
    voucherSerial: "W26-839201",
  },
  {
    id: "ord-1014",
    reference: "SDH-GH-2026-94825",
    date: "2026-09-08 16:45",
    customerName: "Priscilla Addo",
    recipientPhone: "0277382910",
    network: "AirtelTigo",
    serviceType: "checker",
    productName: "NOVDEC Result Checker 2026",
    amount: 28.0,
    paymentMethod: "wallet",
    status: "failed",
    voucherCode: "2910-5829-3920",
    voucherSerial: "N26-104958",
  },
  {
    id: "ord-1015",
    reference: "SDH-GH-2026-94826",
    date: "2026-09-07 08:15",
    customerName: "Kojo Mensah",
    recipientPhone: "0244192834",
    network: "MTN",
    serviceType: "checker",
    productName: "BECE Placement Checker 2026",
    amount: 15.0,
    paymentMethod: "wallet",
    status: "delivered",
    voucherCode: "3920-1049-5829",
    voucherSerial: "B26-291058",
  },
  {
    id: "ord-1016",
    reference: "SDH-GH-2026-94827",
    date: "2026-09-07 11:30",
    customerName: "Emmanuel Osei",
    recipientPhone: "0249821034",
    network: "MTN",
    serviceType: "checker",
    productName: "WASSCE Result Checker 2026",
    amount: 24.0,
    paymentMethod: "wallet",
    status: "delivered",
    voucherCode: "4829-5829-1049",
    voucherSerial: "W26-392010",
  },
  {
    id: "ord-1017",
    reference: "SDH-GH-2026-94828",
    date: "2026-09-06 14:00",
    customerName: "Akosua Serwaa",
    recipientPhone: "0502847192",
    network: "Telecel",
    serviceType: "checker",
    productName: "WASSCE Result Checker 2026",
    amount: 24.0,
    paymentMethod: "momo_telecel",
    status: "delivered",
    voucherCode: "1049-3920-5829",
    voucherSerial: "W26-482958",
  },
  {
    id: "ord-1018",
    reference: "SDH-GH-2026-94829",
    date: "2026-09-06 16:10",
    customerName: "Yaw Boateng",
    recipientPhone: "0553920194",
    network: "MTN",
    serviceType: "checker",
    productName: "BECE Placement Checker 2026",
    amount: 15.0,
    paymentMethod: "wallet",
    status: "delivered",
    voucherCode: "5829-4829-1049",
    voucherSerial: "B26-104939",
  },
  {
    id: "ord-1019",
    reference: "SDH-GH-2026-94830",
    date: "2026-09-05 09:40",
    customerName: "Priscilla Addo",
    recipientPhone: "0277382910",
    network: "AirtelTigo",
    serviceType: "checker",
    productName: "WASSCE Result Checker 2026",
    amount: 24.0,
    paymentMethod: "wallet",
    status: "delivered",
    voucherCode: "3920-5829-1049",
    voucherSerial: "W26-582948",
  },
  {
    id: "ord-1020",
    reference: "SDH-GH-2026-94831",
    date: "2026-09-05 13:25",
    customerName: "Kojo Mensah",
    recipientPhone: "0244192834",
    network: "MTN",
    serviceType: "checker",
    productName: "NOVDEC Result Checker 2026",
    amount: 28.0,
    paymentMethod: "wallet",
    status: "delivered",
    voucherCode: "1049-4829-5829",
    voucherSerial: "N26-392058",
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-501",
    reference: "TX-SDH-84910",
    date: "2026-09-13 08:05",
    type: "credit",
    category: "wallet_funding",
    amount: 200.0,
    fee: 2.0,
    balanceAfter: 395.5,
    description: "MTN MoMo Wallet Top-up (0244192834)",
    status: "completed",
    channel: "MTN Mobile Money",
  },
  {
    id: "tx-502",
    reference: "TX-SDH-84911",
    date: "2026-09-13 08:47",
    type: "debit",
    category: "purchase",
    amount: 22.5,
    fee: 0.0,
    balanceAfter: 373.0,
    description: "Purchase MTN 5GB for 0244192834",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-503",
    reference: "TX-SDH-84912",
    date: "2026-09-13 09:15",
    type: "debit",
    category: "purchase",
    amount: 24.0,
    fee: 0.0,
    balanceAfter: 349.0,
    description: "WASSCE Result Checker purchase (ord-1003)",
    status: "pending",
    channel: "SDH Wallet",
  },
  {
    id: "tx-504",
    reference: "TX-SDH-84913",
    date: "2026-09-13 09:48",
    type: "debit",
    category: "purchase",
    amount: 20.0,
    fee: 0.0,
    balanceAfter: 329.0,
    description: "AT Airtime Top-up for 0277382910",
    status: "failed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-505",
    reference: "TX-SDH-84914",
    date: "2026-09-13 10:22",
    type: "debit",
    category: "purchase",
    amount: 35.0,
    fee: 0.0,
    balanceAfter: 294.0,
    description: "Telecel 10GB Bundle for 0509837261",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-506",
    reference: "TX-SDH-84915",
    date: "2026-09-13 10:55",
    type: "credit",
    category: "refund",
    amount: 24.0,
    fee: 0.0,
    balanceAfter: 318.0,
    description: "Refund: BECE Checker order ord-1009 (failed)",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-507",
    reference: "TX-SDH-84916",
    date: "2026-09-13 11:30",
    type: "debit",
    category: "purchase",
    amount: 15.0,
    fee: 0.0,
    balanceAfter: 303.0,
    description: "MTN 2GB Daily Bundle for 0244192834",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-508",
    reference: "TX-SDH-84917",
    date: "2026-09-13 12:10",
    type: "credit",
    category: "wallet_funding",
    amount: 100.0,
    fee: 1.0,
    balanceAfter: 403.0,
    description: "Telecel Cash Wallet Top-up (0509837261)",
    status: "completed",
    channel: "Telecel Cash",
  },
  {
    id: "tx-509",
    reference: "TX-SDH-84918",
    date: "2026-09-13 12:45",
    type: "debit",
    category: "purchase",
    amount: 50.0,
    fee: 0.0,
    balanceAfter: 353.0,
    description: "AFA Registration Fee – Kwame Agyapong",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-510",
    reference: "TX-SDH-84919",
    date: "2026-09-13 13:05",
    type: "debit",
    category: "purchase",
    amount: 18.0,
    fee: 0.0,
    balanceAfter: 335.0,
    description: "AT 3GB Bundle for 0277382910",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-511",
    reference: "TX-SDH-84920",
    date: "2026-09-13 13:38",
    type: "debit",
    category: "purchase",
    amount: 45.0,
    fee: 0.0,
    balanceAfter: 290.0,
    description: "ECG Prepaid Electricity – Token for 4982",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-512",
    reference: "TX-SDH-84921",
    date: "2026-09-13 14:10",
    type: "credit",
    category: "promo_credit",
    amount: 5.0,
    fee: 0.0,
    balanceAfter: 295.0,
    description: "Promo credit: New customer bonus",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-513",
    reference: "TX-SDH-84922",
    date: "2026-09-13 14:50",
    type: "debit",
    category: "purchase",
    amount: 30.0,
    fee: 0.0,
    balanceAfter: 265.0,
    description: "MTN 7GB Weekend Bundle for 0244192834",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-514",
    reference: "TX-SDH-84923",
    date: "2026-09-13 15:20",
    type: "debit",
    category: "purchase",
    amount: 12.0,
    fee: 0.0,
    balanceAfter: 253.0,
    description: "Telecel 1GB Daily for 0509837261",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-515",
    reference: "TX-SDH-84924",
    date: "2026-09-13 15:55",
    type: "credit",
    category: "wallet_funding",
    amount: 75.0,
    fee: 0.75,
    balanceAfter: 328.0,
    description: "AT Money Wallet Top-up (0277382910)",
    status: "completed",
    channel: "AT Money",
  },
  {
    id: "tx-516",
    reference: "TX-SDH-84925",
    date: "2026-09-13 16:10",
    type: "debit",
    category: "purchase",
    amount: 24.0,
    fee: 0.0,
    balanceAfter: 304.0,
    description: "WASSCE Result Checker purchase (ord-1010)",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-517",
    reference: "TX-SDH-84926",
    date: "2026-09-13 16:40",
    type: "debit",
    category: "purchase",
    amount: 28.0,
    fee: 0.0,
    balanceAfter: 276.0,
    description: "MTN 8GB Data Bundle for 0244192834",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-518",
    reference: "TX-SDH-84927",
    date: "2026-09-13 17:00",
    type: "debit",
    category: "purchase",
    amount: 50.0,
    fee: 0.0,
    balanceAfter: 226.0,
    description: "AFA Registration Fee – Gifty Mensah",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-519",
    reference: "TX-SDH-84928",
    date: "2026-09-13 17:20",
    type: "credit",
    category: "refund",
    amount: 35.0,
    fee: 0.0,
    balanceAfter: 261.0,
    description: "Refund: Telecel 10GB failed delivery (ord-1008)",
    status: "completed",
    channel: "SDH Wallet",
  },
  {
    id: "tx-520",
    reference: "TX-SDH-84929",
    date: "2026-09-13 17:50",
    type: "debit",
    category: "purchase",
    amount: 40.0,
    fee: 0.0,
    balanceAfter: 221.0,
    description: "MTN 12GB Monthly Bundle for 0244192834",
    status: "completed",
    channel: "SDH Wallet",
  },
];

export const INITIAL_AFA: AfaApplication[] = [
  {
    id: "afa-01",
    reference: "AFA-GH-9382",
    fullName: "Kwame Agyapong",
    phoneNumber: "0243920194",
    ghanaCardNumber: "GHA-728192834-1",
    location: "Kumasi",
    dateOfBirth: "1985-03-15",
    occupation: "Farmer / Agribusiness",
    dateSubmitted: "2026-09-12 14:20",
    status: "approved",
    fee: 50,
    notes: "National ID verified successfully. Tariff activated.",
  },
  {
    id: "afa-02",
    reference: "AFA-GH-9383",
    fullName: "Gifty Mensah",
    phoneNumber: "0558291034",
    ghanaCardNumber: "GHA-829103847-9",
    location: "Accra",
    dateOfBirth: "1990-07-22",
    occupation: "Produce Trader",
    dateSubmitted: "2026-09-12 11:15",
    status: "under_review",
    fee: 50,
    notes: "Awaiting biometric checksum from MoFA portal.",
  },
  {
    id: "afa-03",
    reference: "AFA-GH-9384",
    fullName: "Kojo Mensah",
    phoneNumber: "0244192834",
    ghanaCardNumber: "GHA-592810394-2",
    location: "Tema",
    dateOfBirth: "1988-11-08",
    occupation: "Agribusiness / Produce Retail",
    dateSubmitted: "2026-09-11 16:45",
    status: "under_review",
    fee: 50,
  },
  {
    id: "afa-04",
    reference: "AFA-GH-9385",
    fullName: "Yaw Boateng",
    phoneNumber: "0502847192",
    ghanaCardNumber: "GHA-102938475-3",
    location: "Koforidua",
    dateOfBirth: "1975-05-30",
    occupation: "Cocoa Farmer",
    dateSubmitted: "2026-09-11 10:30",
    status: "approved",
    fee: 50,
  },
  {
    id: "afa-05",
    reference: "AFA-GH-9386",
    fullName: "Akosua Serwaa",
    phoneNumber: "0277382910",
    ghanaCardNumber: "GHA-938201948-4",
    location: "Ho",
    dateOfBirth: "1992-01-18",
    occupation: "Food Logistics",
    dateSubmitted: "2026-09-10 15:10",
    status: "approved",
    fee: 50,
  },
  {
    id: "afa-06",
    reference: "AFA-GH-9387",
    fullName: "Emmanuel Osei",
    phoneNumber: "0249821034",
    ghanaCardNumber: "GHA-482910394-5",
    location: "Cape Coast",
    dateOfBirth: "1980-09-12",
    occupation: "Poultry Farmer",
    dateSubmitted: "2026-09-10 09:20",
    status: "needs_correction",
    fee: 50,
  },
  {
    id: "afa-07",
    reference: "AFA-GH-9388",
    fullName: "Priscilla Addo",
    phoneNumber: "0553920194",
    ghanaCardNumber: "GHA-291039485-6",
    location: "Sunyani",
    dateOfBirth: "1987-04-25",
    occupation: "Maize Trader",
    dateSubmitted: "2026-09-09 13:40",
    status: "approved",
    fee: 50,
  },
  {
    id: "afa-08",
    reference: "AFA-GH-9389",
    fullName: "Abdul Rahman",
    phoneNumber: "0241029384",
    ghanaCardNumber: "GHA-839201948-7",
    location: "Tamale",
    dateOfBirth: "1978-12-03",
    occupation: "Cattle Farming",
    dateSubmitted: "2026-09-09 11:00",
    status: "approved",
    fee: 50,
  },
  {
    id: "afa-09",
    reference: "AFA-GH-9390",
    fullName: "Grace Ansah",
    phoneNumber: "0509837261",
    ghanaCardNumber: "GHA-192837465-8",
    location: "Takoradi",
    dateOfBirth: "1983-08-14",
    occupation: "Fish Processor",
    dateSubmitted: "2026-09-08 17:25",
    status: "approved",
    fee: 50,
  },
  {
    id: "afa-10",
    reference: "AFA-GH-9391",
    fullName: "Daniel Baah",
    phoneNumber: "0271928374",
    ghanaCardNumber: "GHA-583920194-9",
    location: "Bolgatanga",
    dateOfBirth: "1972-06-20",
    occupation: "Grain Wholesale",
    dateSubmitted: "2026-09-08 08:50",
    status: "rejected",
    fee: 50,
  },
  {
    id: "afa-11",
    reference: "AFA-GH-9392",
    fullName: "Mercy Ofori",
    phoneNumber: "0248291034",
    ghanaCardNumber: "GHA-392019485-0",
    location: "Obuasi",
    dateOfBirth: "1986-02-28",
    occupation: "Vegetable Farmer",
    dateSubmitted: "2026-09-07 14:15",
    status: "approved",
    fee: 50,
  },
  {
    id: "afa-12",
    reference: "AFA-GH-9393",
    fullName: "Samuel Kwarteng",
    phoneNumber: "0552910384",
    ghanaCardNumber: "GHA-748392019-1",
    location: "Nkawkaw",
    dateOfBirth: "1981-10-05",
    occupation: "Yam Farm Logistics",
    dateSubmitted: "2026-09-07 10:05",
    status: "approved",
    fee: 50,
  },
  {
    id: "afa-13",
    reference: "AFA-GH-9394",
    fullName: "Janet Owusu",
    phoneNumber: "0501928374",
    ghanaCardNumber: "GHA-839201948-2",
    location: "Goaso",
    dateOfBirth: "1984-07-11",
    occupation: "Cocoa Produce Buyer",
    dateSubmitted: "2026-09-06 16:30",
    status: "approved",
    fee: 50,
  },
  {
    id: "afa-14",
    reference: "AFA-GH-9395",
    fullName: "Ibrahim Musah",
    phoneNumber: "0278392019",
    ghanaCardNumber: "GHA-291049583-3",
    location: "Damongo",
    dateOfBirth: "1976-03-22",
    occupation: "Shea Butter Retail",
    dateSubmitted: "2026-09-06 12:10",
    status: "approved",
    fee: 50,
  },
  {
    id: "afa-15",
    reference: "AFA-GH-9396",
    fullName: "Evelyn Appiah",
    phoneNumber: "0247382910",
    ghanaCardNumber: "GHA-948302910-4",
    location: "Madina",
    dateOfBirth: "1989-05-17",
    occupation: "Agro-input Dealer",
    dateSubmitted: "2026-09-05 09:15",
    status: "approved",
    fee: 50,
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: "cmp-01",
    ticketNumber: "TKT-SDH-1049",
    orderReference: "SDH-GH-2026-94814",
    category: "delivery_delay",
    subject: "MTN 2.5GB delivery taking longer than 5 minutes",
    status: "investigating",
    priority: "high",
    createdAt: "2026-09-11 16:52",
    lastUpdated: "2026-09-11 16:56",
    messages: [
      {
        id: "m1",
        sender: "customer",
        senderName: "Yaw Boateng",
        text: "Hello, my MoMo was debited GH₵12 for the 2.5GB bundle but beneficiary has not received the SMS yet.",
        timestamp: "16:52",
      },
      {
        id: "m2",
        sender: "support_admin",
        senderName: "SDH NOC Support (Abena)",
        text: "Hi Yaw, we see MTN Ghana experienced a brief gateway queue between 16:48 and 16:55. Your order SDH-GH-2026-94814 is in the active dispatch queue. It will complete in 2-3 minutes. If it fails, our system automatically refunds your wallet.",
        timestamp: "16:56",
      },
    ],
  },
];

export const INITIAL_STORE_CONFIG: AgentStoreConfig = {
  agentName: "Kofi Owusu",
  storeName: "Kofi Telecom Express",
  handle: "kofi-telecom",
  tagline: "Instant Non-Expiry Data & Exam Vouchers in Ghana",
  announcement:
    "🔥 Fast delivery within 60 seconds! 24/7 WhatsApp customer support.",
  whatsappNumber: "0244192834",
  phone: "0244192834",
  email: "kofitelecom@gmail.com",
  status: "published",
  themeColor: "#2563eb",
  bannerGradient: "linear-gradient(135deg, #1e3a8a 0%, #2563eb 100%)",
  defaultNetwork: "MTN",
  marginMarkupPercent: 8,
  customPrices: {
    "mtn-1gb": 5.5,
    "mtn-2.5gb": 12.0,
    "mtn-5gb": 22.5,
    "mtn-10gb": 43.0,
    "telecel-5gb": 20.0,
    "telecel-10gb": 39.0,
    "at-5gb": 18.5,
    "at-10gb": 35.0,
  },
  allowGuestCheckout: true,
  storeLogo: null,
  whatsappChannelUrl: "https://whatsapp.com/channel/0029Va9KofiTelecomGhana",
  enabledNetworks: ["MTN", "Telecel", "AirtelTigo"],
  enabledServices: {
    airtime: true,
    checker: true,
    afa: false,
  },
  promoCodes: [
    {
      code: "WELCOME10",
      type: "percent",
      value: 10,
      discountPercent: 10,
      scope: "all",
      uses: 0,
      active: true,
    },
    {
      code: "FLASH5",
      type: "percent",
      value: 5,
      discountPercent: 5,
      scope: "all",
      uses: 0,
      active: true,
    },
    {
      code: "STUDENT",
      type: "percent",
      value: 3,
      discountPercent: 3,
      scope: "all",
      uses: 0,
      active: true,
    },
  ],
};

export const INITIAL_PAYOUTS: PayoutRequest[] = [
  {
    id: "pay-01",
    reference: "PAY-SDH-3910",
    agentId: "ag-kofi",
    agentName: "Kofi Owusu (Kofi Telecom)",
    amount: 350.0,
    fee: 3.5,
    netAmount: 346.5,
    momoNetwork: "MTN",
    momoNumber: "0244192834",
    accountName: "Kofi Owusu",
    requestDate: "2026-09-11 11:20",
    status: "approved",
    riskScore: "low",
    notes: "Regular agent, high volume, 0 chargebacks.",
  },
  {
    id: "pay-02",
    reference: "PAY-SDH-3911",
    agentId: "ag-efya",
    agentName: "Efya Mensah (Accra Data Hub)",
    amount: 820.0,
    fee: 8.2,
    netAmount: 811.8,
    momoNetwork: "Telecel",
    momoNumber: "0501829304",
    accountName: "Efya Mensah",
    requestDate: "2026-09-11 14:45",
    status: "pending",
    riskScore: "low",
    notes: "KYC Verified agent. 32 orders delivered today.",
  },
];

export const INITIAL_SMS_CAMPAIGNS: BulkSmsCampaign[] = [
  {
    id: "sms-01",
    title: "Weekend Promo Special",
    senderId: "KOFIDATA",
    message:
      "Hello valued customer! Enjoy 10GB MTN data for just GH₵43 today only at smartdatahub.com/store/kofi-telecom. Instant delivery.",
    recipientCount: 145,
    costPerSms: 0.05,
    totalCost: 7.25,
    pagesPerSms: 1,
    dateCreated: "2026-09-10 09:00",
    status: "sent",
    deliveryRatePercent: 98.6,
  },
];

export const INITIAL_GATEWAYS: TelecomGateway[] = [
  {
    id: "gw-mtn-evd",
    name: "MTN Ghana EVD Dispatch",
    network: "MTN",
    status: "online",
    latencyMs: 42,
    successRate: 99.8,
    lastPing: "Just now",
  },
  {
    id: "gw-telecel-api",
    name: "Telecel Ghana Core Switch",
    network: "Telecel",
    status: "online",
    latencyMs: 65,
    successRate: 99.4,
    lastPing: "1s ago",
  },
  {
    id: "gw-at-direct",
    name: "AirtelTigo / AT Fast Switch",
    network: "AirtelTigo",
    status: "online",
    latencyMs: 58,
    successRate: 98.9,
    lastPing: "2s ago",
  },
  {
    id: "gw-waec-host",
    name: "WAEC National Examinations Server",
    network: "WAEC",
    status: "online",
    latencyMs: 110,
    successRate: 99.1,
    lastPing: "5s ago",
  },
  {
    id: "gw-mofa-afa",
    name: "Ministry of Food & Agric (AFA Portal)",
    network: "MOFA",
    status: "online",
    latencyMs: 145,
    successRate: 97.8,
    lastPing: "12s ago",
  },
  {
    id: "gw-ecg-power",
    name: "ECG PowerApp Prepaid Gateway",
    network: "ECG",
    status: "online",
    latencyMs: 88,
    successRate: 99.2,
    lastPing: "3s ago",
  },
];

// Convenience Aliases
export const initialBundles = INITIAL_BUNDLES;
export const mockOrders = INITIAL_ORDERS;
export const mockTransactions = INITIAL_TRANSACTIONS;
export const mockAfaApplications = INITIAL_AFA;
export const mockResultCheckers = INITIAL_CHECKERS;
export const mockGateways = INITIAL_GATEWAYS;
export const mockAgentStore = INITIAL_STORE_CONFIG;
export const mockComplaints = INITIAL_COMPLAINTS;

// Ghana Telecom network auto-detection helper
export function detectGhanaNetwork(phone: string): TelecomNetwork {
  const cleaned = phone.replace(/\D/g, "");
  const prefix = cleaned.startsWith("233")
    ? "0" + cleaned.slice(3, 5)
    : cleaned.slice(0, 3);

  // MTN Prefixes: 024, 054, 055, 059, 053
  if (["024", "054", "055", "059", "053"].includes(prefix)) {
    return "MTN";
  }
  // Telecel Prefixes: 020, 050
  if (["020", "050"].includes(prefix)) {
    return "Telecel";
  }
  // AirtelTigo / AT Prefixes: 027, 057, 026, 056
  if (["027", "057", "026", "056"].includes(prefix)) {
    return "AirtelTigo";
  }
  return "MTN"; // Default fallback
}

// Local Storage Helper with Fallback
export function loadFromStorage<T>(key: string, fallback: T): T {
  try {
    const rawKey = key.startsWith("sdh_") ? key.slice(4) : key;
    const storageKey = `sdh_${rawKey}`;
    const item = localStorage.getItem(storageKey);
    if (!item) return fallback;
    const parsed = JSON.parse(item);

    if (rawKey.includes("orders") && Array.isArray(parsed)) {
      const fallbackMap = new Map(
        (fallback as any[]).map((o: any) => [o.id, o]),
      );
      const updatedParsed = parsed.map((o: any) => {
        const fb = fallbackMap.get(o.id);
        if (fb && fb.serviceType === "checker") {
          return {
            ...o,
            status: fb.status,
            date: fb.date,
            recipientPhone: fb.recipientPhone ?? o.recipientPhone,
          };
        }
        return o;
      });

      const existingIds = new Set(updatedParsed.map((o: any) => o.id));
      const missingCheckers = (fallback as any[]).filter(
        (o: any) => o.serviceType === "checker" && !existingIds.has(o.id),
      );
      const merged = [...updatedParsed, ...missingCheckers];
      saveToStorage(rawKey, merged);
      return merged as T;
    }

    if (rawKey.includes("afa_apps") && Array.isArray(parsed)) {
      if (parsed.length < 5 && Array.isArray(fallback)) {
        const existingIds = new Set(parsed.map((a: any) => a.id));
        const missingApps = (fallback as any[]).filter(
          (a: any) => !existingIds.has(a.id),
        );
        const merged = [...parsed, ...missingApps];
        saveToStorage(rawKey, merged);
        return merged as T;
      }
    }
    return parsed;
  } catch {
    return fallback;
  }
}

export function saveToStorage<T>(key: string, value: T): void {
  try {
    const rawKey = key.startsWith("sdh_") ? key.slice(4) : key;
    const storageKey = `sdh_${rawKey}`;
    localStorage.setItem(storageKey, JSON.stringify(value));
  } catch (e) {
    console.error("Storage error", e);
  }
}
